In [1]:
import numpy as np
matrix = np.array([[10,20,30],
                   [40,50,60],
                   [70,80,90]])

print("Matrix:")
print(matrix)

print("Row Sum:", np.sum(matrix, axis=1))
print("Column Sum:", np.sum(matrix, axis=0))

print("Row Mean:", np.mean(matrix, axis=1))
print("Column Mean:", np.mean(matrix, axis=0))

Matrix:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Row Sum: [ 60 150 240]
Column Sum: [120 150 180]
Row Mean: [20. 50. 80.]
Column Mean: [40. 50. 60.]
