In [1]:
import numpy as np
# Create random matrices
X = np.random.randint(1,10,(2,2))
Y = np.random.randint(1,10,(2,2))

print("Matrix X:")
print(X)

print("Matrix Y:")
print(Y)

print("Addition:")
print(X+Y)

print("Multiplication:")
print(np.dot(X,Y))

Matrix X:
[[7 6]
 [3 3]]
Matrix Y:
[[9 3]
 [1 8]]
Addition:
[[16  9]
 [ 4 11]]
Multiplication:
[[69 69]
 [30 33]]
