In [1]:
import numpy as np
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)
addition = A + B
print("Matrix Addition:")
print(addition)
subtraction = A - B
print("Matrix Subtraction:")
print(subtraction)

multiplication = np.dot(A,B)

print("Matrix Multiplication:")
print(multiplication)

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix Addition:
[[ 6  8]
 [10 12]]
Matrix Subtraction:
[[-4 -4]
 [-4 -4]]
Matrix Multiplication:
[[19 22]
 [43 50]]
