In [1]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Matrix:")
print("First two rows:")
print(arr[:2])


print("Last two columns:")
print(arr[:,1:])


Matrix:
First two rows:
[[1 2 3]
 [4 5 6]]
Last two columns:
[[2 3]
 [5 6]
 [8 9]]
