In [1]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr1 = np.array([1,2,3,4,5,6])

arr2 = arr1.reshape(2,3)

arr3 = arr1.reshape(1,2,3)

print("1D Array:", arr1)
print("2D Array:")
print(arr2)
print("3D Array:")
print(arr3)

1D Array: [1 2 3 4 5 6]
2D Array:
[[1 2 3]
 [4 5 6]]
3D Array:
[[[1 2 3]
  [4 5 6]]]
