In [2]:

import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print("Matrix:")
print(arr)

print("Element:", arr[1,2])

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element: 6
