In [1]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
a = np.array([1,2,3])
b = np.array([4,5,6])


vstack = np.vstack((a,b))


hstack = np.hstack((a,b))

print("Vertical Stack:")
print(vstack)

print("Horizontal Stack:")
print(hstack)

Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]
